### ISSUE TITLE
cannot install NativeScript Sidekick on Archlinux

### ISSUE THREAD

**Issue by Fluqz** [NativeScript/sidekick-feedback#117]
Hey, im trying to install NativeScript and NativeScript Sidekick on a Arch Linux VM.

Already installed NativeScript
`sudo npm i -g nativescript`
`tns --version` outputs `3.4.0`

Then trying to install the sidekick project with yaourt (nativescript-sidekick 1.1.0.v.2017.12.21.2-1 in AUR) throws the following error:

> Validating source_x86_64 files with sha512sums...
    NativeScriptSidekick-amd64.deb ... FAILED
==> ERROR: One or more files did not pass the validity check!
==> ERROR: Makepkg was unable to build nativescript-sidekick.

**Comment by bundyo** [comment]
Unfortunately Arch Linux is not among the list of our supported Linux distributions at this time. 

That said, you can post the verbose output of your error which may help us support it in the future, if we decide to.

**Comment by Fluqz** [comment]
Which command should I use for output? the pacman.log? Or does yaourt uses its own?

**Comment by bundyo** [comment]
On a second thought, it seems you're trying to install the deb package as it has its source available, which NativeScript Sidekick doesn't provide. However you can still install deb packages in Arch Linux, without converting them. 

Check [this Stack Exchange post](https://unix.stackexchange.com/questions/83540/installing-a-deb-package-on-arch-is-it-possible) for more information and let me know if this helps.

**Comment by Fluqz** [comment]
The package provided from the AUR is not a deb file, its a tar.gz. On second though im not gonna use NativeScript.

**Comment by bundyo** [comment]
Okay, I didn't expect this - found the package you're talking about, but unfortunately it is not provided by us - someone else posted it in AUR without our consent. In the PKGBUILD file in the repo you can see that it directly downloads the deb file from our CDN and extracts its data.tar.gz and installs the content in its expected location:

```bash
source_x86_64=(".../linux/NativeScriptSidekick-amd64.deb")

package() {
        tar xf data.tar.xz -C "${pkgdir}"

        install -d "${pkgdir}/${pkgname}/opt"
        install -d "${pkgdir}/${pkgname}/usr/share"
}
```

In theory it should work, but since we pushed an update on 5 January 2018, the SHA download verification fails and that's your error. I guess you can contact the maintainer of this package, so that he can update it and then you can install it. It sure is equivalent of installing the deb file directly, but at least you may have automatic updates when the maintainer updates it.

Still, while NativeScript Sidekick is currently not open source, NativeScript itself is, along with its CLI, so if you don't want to use non-OSS, you can use only them. Check [this page](https://docs.nativescript.org/start/ns-setup-linux) for more information about that. The instructions are for Ubuntu, but you can at least see what dependencies you need.

Hope this helps.

**Comment by popcor255** [comment]
Try installing using:
https://aur.archlinux.org/packages/nativescript-sidekick/

Once your done installing it will give you an error saying it cant find 'nativescript sidekick'.
go to your usr/share folder and change 'nativescript sidekick' to 'nativescript-sidekick' and it should work.
