### ISSUE TITLE
Webpack option is disabled with latest template-drawer-navigation-ng

### ISSUE THREAD

**Issue by SaltyDH** [NativeScript/sidekick-feedback#200]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
The Build using Webpack Sidekick option is disabled for my project which I reproduced by using the template-drawer-navigation-ng template. This means that my project throws errors because its configured to work only with a webpack build.

### Which platform(s) does the issue occur on?
Windows 10
Both Android & iOS builds are affected.

### Provide the following version numbers that the issue occurs with:

- NativeScript Sidekick Desktop: Version: 1.10.1-v.2018.5.24.5
- NativeScript CLI: 4.0.2
- CLI extension nativescript-cloud: 1.10.0
- CLI extension nativescript-starter-kits: 0.3.4
- Package json is configured with nativescript-dev-webpack: next in these templates

### Tell us how to recreate the issue in as much detail as possible
1. tns create a new app from the template
2. Open Sidekick
3. Find the Webpack option under the Build section and see that its grayed out.

### Does this issue happen every time?
Yes

**Comment by tsvetie** [comment]
Hey @SaltyDH,

I tested the scenario you describe, but I could not reproduce the problem with a newly created app. I guess you actually get this behavior with an app that you have been working on for a while. If this is the case, due to new features that required this, we increased the minimum required version of the _nativescript-dev-webpack_ plugin to _0.10.1_. That means that you need to update the version of this plugin in your project in order to enable the webpack option. I would recommend that you update to the latest version of the plugin.

**Comment by tsvetie** [comment]
Yes, this is a limitation that we currently have - we get the installed version of "nativescript-dev-webpack" from the package.json file of your app. Great that you were able to fix this quickly.
