### ISSUE TITLE
Livesync keeps failing, cannot write to dest file

### ISSUE THREAD

**Issue by delanick** [NativeScript/sidekick-feedback#205]
Hi, I keep getting the below errors when saving my code and then have to click on 'Run on Device' as the livesync fails. Please advise what I may be doing wrong.

`[18-06-07 21:48:42.093] (CLI) cp: copyFileSync: could not write to dest file (code=EACCES):/Users/nickdelahunt/Documents/OneDrive/wigital/Mobile apps/MobiWasSA/Project FIles/MobiWash/MobiWashSA/platforms/ios/MobiWashSA/app/media/menu_18pt_1x.png`

**Comment by tsvetie** [comment]
Hi @delanick,

Can you check whether the problem is only when you LiveSync - that is, can you build the application successfully? 

I am guessing that you are trying to build/run-on-device a project that is on a drive that you or someone else mounted. Can you check the permissions of the project folder? You should make sure that you are the owner of the project folder and that you have read and write access for all folders in the path _/Users/nickdelahunt/Documents/OneDrive/wigital/Mobile apps/MobiWasSA/Project FIles/MobiWash/MobiWashSA_.

**Comment by ggarabedian** [comment]
We are closing this issue due to prolonged period of inactivity. If the issue is still present in the latest version of Sidekick and you would like us to investigate it further, please feel free to create a new issue with up-to-date information.

Thank you!
