### ISSUE TITLE
Unable to get past installing NativeScript CLI on Windows 10

### ISSUE THREAD

**Issue by dwheelerjr** [NativeScript/sidekick-feedback#207]
I have submitted the issue as a comment on "Nativescript CLI fails to install from sidekick #135". I was told to make a seperate issue and attach the logs here.

I have recently deleted the sidekick app and then reinstalled it with the newest version 1.10.2.0

I get the following result:
![image](https://user-images.githubusercontent.com/13876805/41386861-ca8b04aa-6f51-11e8-9568-5616ae33b128.png)

Here are the logs:
[console_18-06-13_21-18-11.631.log](https://github.com/NativeScript/sidekick-feedback/files/2100478/console_18-06-13_21-18-11.631.log)
[main_18-06-13_21-18-16.024.log](https://github.com/NativeScript/sidekick-feedback/files/2100479/main_18-06-13_21-18-16.024.log)
[prerequisites_18-06-13_21-18-23.121.log](https://github.com/NativeScript/sidekick-feedback/files/2100480/prerequisites_18-06-13_21-18-23.121.log)

Any help is appreciated!

**Comment by tsvetie** [comment]
Hey @dwheelerjr,

Great to hear from you again. The log files that you sent contain all the information that I needed. In short, the problem is the version of npm that you have (2.15.12). We do not have a strict requirement for the version of npm - we simply require that you have it. However, some versions of npm contain a bug that prevents NS CLI from installing correctly.

My guess is that at some point you executed a command, similar to the following:
```
npm i -g npm@2.15.12
```

In case this is true, all you need to do is remove that version by executing:
```
npm remove -g npm
```

This should leave you with the version of npm that comes with NodeJS. You can check whether this is true by executing:
```
npm --version
```
This command should output "5.6.0".

**Comment by dwheelerjr** [comment]
![image](https://user-images.githubusercontent.com/13876805/41411621-7bdb0a80-6fab-11e8-96f1-b675c27d15e9.png)

Ran it and ended up with version 5.8 and still fails. It only produced 1 log file this time.
[prerequisites_18-06-14_08-10-39.649.log](https://github.com/NativeScript/sidekick-feedback/files/2102268/prerequisites_18-06-14_08-10-39.649.log)

**Comment by tsvetie** [comment]
Hey @dwheelerjr,

I would expect that Sidekick produces at least a new console log file. Can you try deleting all previous log file from _%appdata%/nativescriptsidekick/logs_, and then running Sidekick again to see what new log files will appear?

Apart from this, can you try the following:
1. Execute ```where npm``` in both an administrator console (_Run as administrator_ - I assume you did exactly this from the image you sent) and none-administrator console. This command should show all your npm installations. This is just to check whether you have other npm installations.
2. Execute ```where tns``` to check if NS CLI installation was successful.
3. Execute ```npm config get prefix``` - this command should output where npm puts globally installed packages. 

Can you send me the output of these commands and the newly created Sidekick logs?

**Comment by dwheelerjr** [comment]
Here are the logs:
[console_18-06-14_12-39-51.676.log](https://github.com/NativeScript/sidekick-feedback/files/2103233/console_18-06-14_12-39-51.676.log)
[main_18-06-14_12-39-55.705.log](https://github.com/NativeScript/sidekick-feedback/files/2103234/main_18-06-14_12-39-55.705.log)
[prerequisites_18-06-14_12-40-03.759.log](https://github.com/NativeScript/sidekick-feedback/files/2103235/prerequisites_18-06-14_12-40-03.759.log)

commands you asked for:
![image](https://user-images.githubusercontent.com/13876805/41426054-80197fd0-6fd0-11e8-8ce3-5efa0923e01d.png)

as admin:
![image](https://user-images.githubusercontent.com/13876805/41426117-b0a371c4-6fd0-11e8-844c-018e6168ebb1.png)

**Comment by tsvetie** [comment]
Hey @dwheelerjr,

The important part in the log files is the following:

```
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\ProgramData\\Microsoft\\VisualStudio\\MDA\\fab01b44\\taco-toolset-6.3.1\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "nativescript@latest" "--ignore-scripts"
npm ERR! node v8.11.1
npm ERR! npm  v2.15.10
npm ERR! path C:\ProgramData\Microsoft\VisualStudio\MDA\fab01b44\taco-toolset-6.3.1\tns.cmd
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall unlink

npm ERR! Error: EPERM: operation not permitted, unlink 'C:\ProgramData\Microsoft\VisualStudio\MDA\fab01b44\taco-toolset-6.3.1\tns.cmd'
```

I guess you installed taco toolset 6.3.1 at some point and it modified the _npm prefix_ for you. I guess this is why initially, you had npm 2.15.10 - you most probably got it with the taco toolset 6.3.1 installation as well. The problem is that your user does not have permissions in the _C:\ProgramData\Microsoft\VisualStudio\MDA\fab01b44\taco-toolset-6.3.1_ folder.

At this point I would recommend that you change the npm prefix back to its original location. Please note that this means that you will have to install again all packages that you currently have installed globally. As you can check in [npm documentation](https://docs.npmjs.com/files/folders#prefix-configuration), the prefix config defaults to _%AppData%\npm_ for Windows. So my suggestion is to set it there:

```
npm config set %AppData%\npm
```

Your user has permissions in that folder so you will no longer need to use an administrator console when installing npm packages globally.

**Comment by yoat** [comment]
If "where tns" returns "Could not find files for the given pattern(s)" then you should check your path. For whatever reason Node did not add its bin folder to my path (even after a restart).  'npm' was accessible from that directory, but 'tns' was not.  Manually adding the explicit %AppData%/npm folder to my PATH variable resolved the problems and allowed Sidekick installation to complete.

**Comment by ggarabedian** [comment]
Thank you for sharing this information @yoat!
 
We are closing this issue due to prolonged period of inactivity. If the issue is still present in the latest version of Sidekick and you would like us to investigate it further, please feel free to create a new issue with up-to-date information.

Thank you! 😃
