### ISSUE TITLE
Sidekick loads old CSS on app crash in Live Sync

### ISSUE THREAD

**Issue by markosole** [NativeScript/sidekick-feedback#211]
**### Did you verify whether this issue has already been reported here?**
Yes

**### Tell us about the problem**
When I build app and LiveSync it on device and app crashes (for any reason - error in code etc), Sidekick loads old CSS file. I am using Template: JavaScript - Drawer Navigation. Its css (app-root.android.css) gets reloaded to defaults. I have noticed that same thing happen when I close and reopen same project in Sidekick and Run on Device. It resets CSS. 

**### Which platform(s) does the issue occur on?**
Android Oreo, Windows 10 as build system.

**### Provide the following version numbers that the issue occurs with:**
Version: 1.10.2-v.2018.6.5.2 (latest)
NativeScript CLI version: 4.1.0
CLI extension nativescript-cloud version: 1.11.0
CLI extension nativescript-starter-kits version: 0.3.4

 NativeScript Sidekick Desktop , Sidekick for Visual Studio  
  
**### Does this issue happen every time?**
Yes

I am new to nativescript and sidekick. I could not find any information about rebuilding css and reason why this happens. 
Thanks.

**Comment by ggarabedian** [comment]
Hello @markosole,

Based on your description of the issue and your statement that you are new to NativeScript, I assume that you are modifying the CSS files (for example, app-root.android.css) directly and not through the SCSS files. The Drawer Navigation template uses SCSS files to manage the application styling and you should modify those files instead of the CSS ones. By default, the **app-root.android.css** file is transpiled from the **_app-root-common.scss** file. You can place your custom styling in the **app-root.android.scss** as well.

To explain in more detail, on each LiveSync the SCSS files are transpiled to CSS and the changes are reflected in your deployed application. While modifying the CSS files directly will LiveSync the changes to your deployed app and update it visually, they are not permanent and will be removed as soon as the SCSS is transpiled again (for example when the app crashes, or when you restart the LiveSync). The only way to avoid this is to make the changes directly in the SCSS files. 

Alternatively, if you do not want to use SASS files, you can start from the Blank JavaScript template.

Having said that, if the above is not helpful or I have misunderstood the issue at hand, I'll ask you to share the Sidekick logs, so we can investigate this further. To access the logs, open Sidekick and select **Help** -> **Show Logs** from the top menu.

**Comment by markosole** [comment]
Hi and thanks for reply. I will try to add my styles to app-root.android.scss  file instead and see results. It that does not help, I will send you a Log for more details.

**Comment by ggarabedian** [comment]
We are closing this issue due to prolonged period of inactivity. If the issue is still present in the latest version of Sidekick and you would like us to investigate it further, please feel free to create a new issue with up-to-date information.

Thank you!
