### ISSUE TITLE
Cloud Build for iOS: Linking FBSDKCore - Build Failed

### ISSUE THREAD

**Issue by ntrpnr** [NativeScript/sidekick-feedback#212]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
Cloud build stops with the message **'Build Failed'** every time. The previous row says **'Linking FBSDKCore'**.

### Which platform(s) does the issue occur on?
iOS
macOS Cloud build
Update: Same for local build on macOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 1.10.2-v.2018.6.5.2
- **NativeScript CLI:** 4.1.0
- **CLI extension nativescript-cloud:** 1.11.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Tell us how to recreate the issue in as much detail as possible
Start a cloud build for iOS

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.github.com/ntrpnr/29cc2b4a6b3f260bb15c156a81fc6056

**Comment by ntrpnr** [comment]
I have identified the following:
* I have no references to FBSDKCore in my project.
* I have this in my package.json: ```"nativescript-facebook": "^2.2.2"
* nativescript-facebook has the following lines in its Podfile:
```
pod 'FBSDKCore**Kit**', '~> 4.7'
pod 'FBSDKLoginKit', '~> 4.7'
```

**Comment by ggarabedian** [comment]
Hello @ntrpnr,

You are correct, the error is occurring during the linking of the FBSDKCore library, which is a dependency of the NativeScript Facebook plugin. However, this does not necessary mean that the issue is related to this particular plugin. I did several attempts to reproduce the reported issue with an app that has the Facebook plugin, but without success. 

I noticed in [the provided logs](https://gist.github.com/ntrpnr/29cc2b4a6b3f260bb15c156a81fc6056#file-nativescript-sidekick-log-L78) that your app contains the [nativescript-nfc plugin](https://github.com/EddyVerbruggen/nativescript-nfc), which is outdated and doesn't seem to support NativeScript 4.x versions. The fastest way to determine if this plugin is causing the problem is to remove it and then try to build. If this is the case, I recommend that you open a new issue in the repository of the plugin.

Additionally, if the issue is related to the nativescript-nfc plugin, you might want to check if you have enabled the [NFC Tag Reading of the specific App ID in the Apple Developer Center](https://stackoverflow.com/questions/44380305/ios-11-core-nfc-any-sample-code) (and then regenerate your provisioning profile). I noticed that this step isn't mentioned in the plugin repository and might be actually causing the problem.

**Comment by ntrpnr** [comment]
@ggarabedian Tried to remove to nativescript-nfc plugin and got a different error:
```
Cannot find module 'nativescript-custom-entitlements/lib/before-prepare.js'
```

So I guess the original error was related to this package.

**Comment by ntrpnr** [comment]
@ggarabedian I've posted a new issue #214 for this error.

**Comment by ntrpnr** [comment]
Update: Enabling NFC Tag reading for the App ID solved this issue. Thank you so much. You can close the issue.

**Comment by ggarabedian** [comment]
@ntrpnr, I am happy to hear that enabling the NFC Tag Reading resolved the issue
