### ISSUE TITLE
SideKick cloud build takes 13-20 minutes

### ISSUE THREAD

**Issue by bgpedersen** [NativeScript/sidekick-feedback#215]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I have installed all requirements and followed all instructions but building any size apps (with webpack, clean/noclean) release app in the cloud using SideKick for Android and iOS takes from 13-20 minutes each. This seems unreasonable and dull.

### Which platform(s) does the issue occur on?
Both platforms
Windows 10

### Provide the following version numbers that the issue occurs with:
200mbs internet connection
16gb RAM
Node version 8.9.0 
NativeScript SideKick Desktop Version: 1.10.3-v.2018.6.26.1 (latest)
NativeScript CLI version: 4.1.0
CLI extension nativescript-cloud version: 1.11.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Open SideKick
2. Select Built
3. Click build for Android or iOS with Cloud, Release, Webpack & clean/noclean

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.github.com/Moelgaard85/e2cbecef52227f34ec9c55af9a29421a

**Comment by Moelgaard85** [comment]
I dont know if it is connected, but later the same day while keep trying building and waiting for the build to complete, i got an internal server error from your servers in the CLI. The build never completed afterwards also.

```
[18-06-28 16:23:04.555] (CLI) (node:12220) Error: The server returned unexpected response: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>1940A6F0CD70C048</RequestId><HostId>8nfv4gD5ltYwZutSmoAy5naujSr4D/lT2sObfd2hkg5qMG5+we4g3xItJidCGpHlW+Yz5VZwrHY=</HostId></Error>
    at IncomingMessage.responseStream.on (C:\Users\Stationaer\AppData\Roaming\npm\node_modules\nativescript\lib\common\http-client.js:133:45)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:12220) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by tsvetie** [comment]
Hey @Moelgaard85,

I will start with the second problem that you described - this is a sporadic error. We are aware of it and currently, we are working on a fix. It is not related to the problem you initially reported.

Now, regarding the first problem you mentioned - the fact that the build takes 13+ minutes to complete. I noticed that you are building in Release mode - can you confirm whether you can reproduce the problem today as well (we had some problems with npm yesterday) and whether you get the same result when building in Debug mode (try a couple of times)?

Please note that Release builds will always be much slower than any Debug build (excluding the first Debug build) as they are "clean" while Debugs builds after the first one are incremental. This is intentional, as people usually build in Release mode towards the end of their development process and in order to publish their app. Our idea is that release packages, especially the ones, built in order to be published, should not reuse files from previous builds.

**Comment by bgpedersen** [comment]
Since nothing was resolved, im closing the issue.
