### ISSUE TITLE
App crashes without any errors.

### ISSUE THREAD

**Issue by ShyshkovOleg** [NativeScript/sidekick-feedback#232]
My app crashes without any errors. I Use sidekick to build on IOS.
Did you made any updates to sidekick yesterday? I'm asking because without any changes in my code app started to crash. I'm able to build, install on physical device but It crashes on launch. Yesterday I launched it successfully.
- Windows 10, 64
- "tns-ios": {"version": "4.1.1"} 
-  "webpack": "~4.6.0",
I've tried to remove platform, tried to use a Clean Build, I've even tried to build with previous commits(with removing platform every time) - do not resolve the issue.
- Log:  
[sideKick log.docx](https://github.com/NativeScript/sidekick-feedback/files/2205267/sideKick.log.docx)
- package.json:
[packageJSON.txt](https://github.com/NativeScript/sidekick-feedback/files/2205272/packageJSON.txt)

I've tried to build withOUT webpack and the error is next:
- error: exportArchive: fse.node has conflicting provisioning settings.
[build WITHOUT Webpack.docx](https://github.com/NativeScript/sidekick-feedback/files/2205531/build.WITHOUT.Webpack.docx)
- new certificates and provisioning was generated before(platform remove/add ios too).

Please, I need your help. I could send you my app to inspect if you need.

**Comment by tsvetie** [comment]
Hey @ShyshkovOleg,

Can you try starting the application manually on the device to see if it will start correctly? 

I looked through the logs you provided and the error basically says that the application is deployed successfully and that we cannot start it on the device for you. In order to be able to launch an application on iOS device, the device needs to have a mounted developer disk image. The developer disk images are distributed with XCode on Mac and are not available on Windows. As the error message says you need to start the app manually on the device.

**Comment by ShyshkovOleg** [comment]
Hi, @tsvetie. The app crashes when Im trying to launch it on device. The launchscreen appears and after few second app closes. I've tried to launch it on Iphone 7, Ipod - the same situation. 
It very weird. I've tried so solve the issue #377 and changed detection stategi to default after I received the error BUILD FAILED. I've changed it back, app succesfully instaled on device but started to crash on launch. 
As I mentioned I,ve tried previous code (commits) but it didnt helped me. I will try to reinstall node modules and let you know.

**Comment by Eliyanan** [comment]
Hey @ShyshkovOleg I'm facing the same problem, sidekick won't start, the Error is **getaddrinfo ENOTFOUND market.nativescript.org market.nativescript.org:443** As you posted... Please help
