### ISSUE TITLE
Android Cloud Build Failure

### ISSUE THREAD

**Issue by kwilliamsnucleus** [NativeScript/sidekick-feedback#247]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
When trying to perform a cloud build for Android, command "make" is not found on the cloud server attempting the build:

> gyp ERR! stack Error: not found: make

### Which platform(s) does the issue occur on?
Android <br/>
Windows

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop:** 1.11.1-v.2018.7.17.4 
- **NativeScript CLI:** 4.1.0
- **CLI extension nativescript-cloud:** 1.13.0
- **CLI extension nativescript-starter-kits:** 0.3.4

### Tell us how to recreate the issue in as much detail as possible
1. Do not choose a certificate for cloud building for Android (there is no warning message saying a certificate is required for Android cloud builds).
2. Click build.

### Does this issue happen every time?
Yes

### Send the client logs
Gist with logs: https://gist.github.com/kwilliamsnucleus/ebee579bcebfa831c085b9a52bcb90d4

**Comment by ggarabedian** [comment]
Hello @kwilliamsnucleus,

The issue is related to the [node-usb module](https://github.com/tessel/node-usb) (or a module that depends on it), because it does not have a [pre-compiled binary for Linux](https://gist.github.com/kwilliamsnucleus/ebee579bcebfa831c085b9a52bcb90d4#file-android-cloud-build-failure-logs-L27) and instead is attempting to compile the binary on the cloud machines.

Currently, we do not have **make** on our build machines and we do not plan on introducing it. Our understanding is that any module that requires such components to compile a binary successfully must also offer a pre-compiled binary, which can be downloaded from GitHub. For example, the same app will build successfully for iOS because node-usb offers a pre-compiled binary for macOS. There is a quite old [request for pre-compiled binary for Linux](https://github.com/tessel/node-usb/issues/78) in the node-usb repository, but I assume the Linux OS is not a priority for the developer.

Having said that, I am sorry to say that you won't be able to build in the cloud for Android with the node-usb module. If you do not have this module in your app, can you please share the content of your **package.json** file so we can see which plugin is using it as a dependency (and eventually try to offer you an alternative for it).

**Comment by kwilliamsnucleus** [comment]
@ggarabedian, all I know is the Nativescript plugin repo still has the "nativescript-arduino-usb" plugin available, though it is no longer publicly available on github, nor supported anywhere that I can tell. That is the only plugin I have in my app that I would assume has something to do with node-usb. Package.json: 

> {
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.FTDIUSB",
    "tns-android": {
      "version": "4.1.3"
    }
  },
  "dependencies": {
    "@angular/core": "6.1.1",
    "nativescript-arduino-usb": "1.0.1",
    "nativescript-theme-core": "~1.0.4",
    "rxjs": "6.2.2",
    "tns-core-modules": "4.1.1"
  },
  "devDependencies": {
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-webpack": "~0.14.0"
  }
}

**Comment by ggarabedian** [comment]
@kwilliamsnucleus, thank you for sharing the package.json file of your project. 

Your assumptions seems to be correct, because all other dependencies in your package.json are quite common and we haven't identified any problems with them. Unfortunately, as you have already noticed, the **nativescript-arduino-usb** plugin is not publicly available and we cannot inspect its code or dependencies. We will try to get in touch with the plugin developer to see if there is a way to resolve this issue.

Additionally, we were not able to find a viable alternative to the nativescript-arduino-usb plugin or a way to workaround the lack of pre-compiled binary of the **node-usb** module for Linux. With this in mind, for the time being, the only way to build an app that contains the nativescript-arduino-usb plugin for Android is to do so locally. As I mentioned before, cloud builds for iOS should work as expected even with the above-mentioned plugin.

We are sorry for any inconvenience caused by this limitation and while I cannot make any promises, we will investigate further our options to resolve this issue.

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.

**Comment by kapilt61** [comment]
Hi Guys,

Android build is getting failed. Please check the logs.

` Could not resolve all dependencies for configuration ':app:_F0F1F2F3F4F5F6F7F8F9DebugApkCopy'.
   > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:1.4.
     Required by:
         project :app
      > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:1.4.
         > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'.
            > Could not GET 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'. Received status code 502 from server: Bad Gateway
      > Could not resolve br.com.mobilemind.api:mobilemind-droid-util:1.4.
         > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'.
            > Could not GET 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-droid-util/1.4/mobilemind-droid-util-1.4.pom'. Received status code 502 from server: Bad Gateway
   > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
     Required by:
         project :app
      > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
         > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'.
            > Could not GET 'http://nexus.mobilemind.com.br/repository/mobile-mind-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'. Received status code 502 from server: Bad Gateway
      > Could not resolve br.com.mobilemind.api:mobilemind-utils:1.3.
         > Could not get resource 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'.
            > Could not GET 'http://nexus.mobilemind.com.br/repository/mobile-mind-droid-m2/br/com/mobilemind/api/mobilemind-utils/1.3/mobilemind-utils-1.3.pom'. Received status code 502 from server: Bad Gateway`

**Comment by NickIliev** [comment]
@kapilt61 please consider opening a new issue by providing all the needed information requested in the open [a new issue template](https://github.com/NativeScript/sidekick-feedback/issues/new).
