### ISSUE TITLE
Bad module info has stopped working

### ISSUE THREAD

**Issue by mujibjan** [NativeScript/sidekick-feedback#250]
## Please, provide the details below:
I have downloaded nativescript slidekick but while opening it it says Nativescript has stopped working and give this message " Bad module info has stopped working
" I have restarted my pc several times still same problem-- using windows 10### Did you verify whether this issue has already been reported here?
_Yes/No_

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick Desktop or Sidekick for Visual Studio:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _You can obtain the requested information by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **About** from the top menu_
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and inspect the **NativeScript Sidekick** output in the **Output** window._ 

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes/No_

### Send the client logs
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs._ 

>_You can access the logs by following the steps outlined below._
>
>* In NativeScript Sidekick <br/> _Launch Sidekick and select **Help** &#8594; **Show Logs** from the top menu._
>* In NativeScript Sidekick for Visual Studio 2017 <br/> _Launch Visual Studio and select **Sidekick** &#8594; **Show Logs** from the main menu._

**Comment by ggarabedian** [comment]
Hello @mujibjan,

If you are seeing the [bad_module_info dialog](https://images.drivereasy.com/wp-content/uploads/2018/02/img_5a9538a9da575.jpg), the issue is most likely not related to Sidekick, but to the Windows 10 operating system. The suggested approach [to resolve this issue is to downgrade the Windows 10 installation to version 1703](https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/bad-module-info-has-stopped-working/a67de1f7-76a8-4cdc-87c1-a2b3c2c1b39b), which seems a bit harsh way to resolve the problem, but I was not able to find a better alternative.

**Comment by ggarabedian** [comment]
@mujibjan, I just wanted to add that it is possible that the reported behavior is caused by an antivirus program - for example, Malwarebytes seems to cause similar issues. Can you please tell me what kind of antivirus program you use and if possible, you can try to disable it temporary and attempt to run Sidekick.

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.
