### ISSUE TITLE
iOS debugger socket port errors

### ISSUE THREAD

**Issue by CoreyCole** [NativeScript/sidekick-feedback#252]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I'm using sidekick to live reload android and ios simulators simultaneously. I'm using local builds. I'm not using webpack at the moment. When running on device, I get errors:

> NativeScript debugger was not able to get inspector socket port.

> Error: Cannot connect to device socket. The error message is NativeScript debugger was not able to get inspector socket port.

The nativescript sidekick will lose connecting to the device and the "LiveSync" green lightning bolt icon will disappear. This leads me to need to "Run on Device" again in order to get live reloads back.

### Which platform(s) does the issue occur on?
```
iOS simulator version 10.0 (SimulatorApp-851.2 CoreSimulator-518.22)
macOS 10.13.6
```
### Provide the following version numbers that the issue occurs with:
```
Version: 1.12.0-v.2018.8.14.2 (latest)
NativeScript CLI version: 4.2.2
CLI extension nativescript-cloud version: 1.13.0
CLI extension nativescript-starter-kits version: 0.3.4
```

### Tell us how to recreate the issue in as much detail as possible
1. Click "Run on Device" with "Start Debugger" checked
2. I see nativescript splash screen on iOS simulator
3. It crashes to the home screen of the simulator
4. I try manually opening my nativescript app on the iOS simulator by clicking the app icon on the simulator home screen
5. It also crashes to the home screen of the simulator

### Does this issue happen every time?
I need to restart the simulator and sidekick and sometimes it works, sometimes not.

#### errors
https://gist.github.com/CoreyCole/4fff597a943ca4ca8a2dd533b08321d3
 #### full logs along with android
https://gist.github.com/CoreyCole/f28f51a3b22a027faa642b1b15e89d29

**Comment by CoreyCole** [comment]
I'm also getting this error when trying to "Reconnect DevTools" for my iOS simulator `adb` sounds like android, so im confused
```
[18-08-21 12:50:23.424] (CLI) /bin/sh: adb: command not found
[18-08-21 12:50:23.443] (CLI) buffer.js:977
throw new RangeError('Index out of range');
^
RangeError: Index out of range
at checkOffset (buffer.js:977:11)
at Buffer.readInt32BE (buffer.js:1142:5)
at PacketStream._transform (/Users/corey/.npm-global/lib/node_modules/nativescript/lib/device-sockets/ios/packet-stream.js:11:39)
at PacketStream.Transform._read (_stream_transform.js:186:10)
at PacketStream.Transform._write (_stream_transform.js:174:12)
at doWrite (_stream_writable.js:397:12)
at writeOrBuffer (_stream_writable.js:383:5)
at PacketStream.Writable.write (_stream_writable.js:290:11)
at Socket.ondata (_stream_readable.js:639:20)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:607:20)
```

**Comment by tsvetie** [comment]
Hey @CoreyCole,

Can you try to reproduce the problem with the latest NS CLI version - 4.2.3? In order to install it, open a terminal and execute the following command:

```
npm i -g nativescript@latest
```

On a side note, in case you still have the log files of this session, can you send them as well? The log files that Sidekick creates contain a bit more information than we print in the Output pane. You can find the log files by selecting _Show logs_ from the _Help menu_.

Additionally can you explain your scenario in a bit more details. In case I understand correctly, you select both the iOS Simulator and the Android Emulator/device, select _Local Build Type_ and _Start Debugger_ and click _Run on Device_ to start LiveSync with debugging. LiveSync on the iOS simulator starts, DevTools open, but you get the following error:

_NativeScript debugger was not able to get inspector socket port._

At this point, do you see the green lightning bolt icon next to the iOS simulator? Does the build for the Android Emulator/device continue?

After that, you say that you click Reconnect in the DevTools for the iOS simulator and then you get the following error:

_Index out of range_

Does this error happen every time when the first one happens or did you get it only once?

**Comment by CoreyCole** [comment]
Hey @tsvetie, after upgrading to 4.2.3 I've not been able to reproduce the issue. Thank you guys for all the great work on nativescript and sidekick!
