### ISSUE TITLE
NativeScript Sidekick IOS build failed (** ARCHIVE FAILED ** \tCheck dependencies)

### ISSUE THREAD

**Issue by sgornostal** [NativeScript/sidekick-feedback#259]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
IOS clould build failed. Android local build was successfull.

### Which platform(s) does the issue occur on?
iOS

### Provide the following version numbers that the issue occurs with:
√ Getting NativeScript components versions information...
√ Component nativescript has 4.2.3 version and is up to date.
√ Component tns-core-modules has 4.2.0 version and is up to date.
√ Component tns-android has 4.2.0 version and is up to date.
√ Component tns-ios has 4.2.0 version and is up to date.

### Does this issue happen every time?
Yes

### package.json

```
{
  "nativescript": {
    "id": "com.birbars",
    "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~6.1.0",
    "@angular/common": "~6.1.0",
    "@angular/compiler": "~6.1.0",
    "@angular/core": "~6.1.0",
    "@angular/forms": "~6.1.0",
    "@angular/http": "~6.1.0",
    "@angular/platform-browser": "~6.1.0",
    "@angular/platform-browser-dynamic": "~6.1.0",
    "@angular/router": "~6.1.0",
    "nativescript-angular": "~6.1.0",
    "nativescript-bitmap-factory": "^1.7.1",
    "nativescript-geolocation": "^4.3.0",
    "nativescript-google-maps-sdk": "^2.6.1",
    "nativescript-linearprogressbar": "^1.0.4",
    "nativescript-permissions": "^1.2.3",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-sidedrawer": "~4.2.0",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.2.0",
    "tns-core-modules": "~4.2.0",
    "zone.js": "~0.8.18"
  },
  "devDependencies": {
    "codelyzer": "~4.3.0",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.15.0",
    "tslint": "~5.11.0",
    "typescript": "~2.7.2",
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.1.0"
  },
  "readme": "NativeScript Application"
}
```

### Send the client logs
[main_18-09-04_11-59-35.042.log](https://github.com/NativeScript/sidekick-feedback/files/2348120/main_18-09-04_11-59-35.042.log)

**Comment by ampgular** [comment]
Same Error and same situation, build locally but not i the cloud

**Comment by ggarabedian** [comment]
@sgornostal, a local iOS build with the provided package.json file is showing the following error: `The "Swift Language Version" (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.`. The error is caused by the `nativescript-linearprogressbar` plugin, which seems to lack the SWIFT_VERSION build setting (required to build an iOS app with the latest versions of Xcode).

To resolve this issue, you should either contact the plugin developer and ask him to update the plugin accordingly, or alternatively, include the [nativescript-swift-3.0 plugin](https://github.com/naderio/nativescript-swift-3.0) to your app. This plugin will add the necessary build setting and fix the build failure.

@ampgular, the "Archive Failed" error can happen in a lot of different situations. As I have mentioned above, the issue reported by @sgornostal leads to a specific error message when built locally and not an "Archive Failed" message. If the suggested above does not help you to resolve the issue, you should open a new issue and share the produced build logs there. This will help us to investigate this problem further and eventually suggest a way to resolve it, or at least work around it.

**Comment by sgornostal** [comment]
Thanks @ggarabedian ! nativescript-swift-3.0 plugin resolved my issue

**Comment by ampgular** [comment]
thanks @ggarabedian I would check it and then open an issue when necessary

**Comment by ampgular** [comment]
@ggarabedian my error appeared adter I installed the photo-editor pluggin. I taked a look that in the ios platform folder eas a xbuild file with swift annotations, therefore I followed the same recipe, installing the  nativescript-swift-3.0 plugin and now works perfectly. thanks

**Comment by ggarabedian** [comment]
@sgornostal and @ampgular, I am happy to hear that the suggestion to use the nativescript-swift-3.0 plugin helped to resolve both issues!
