### ISSUE TITLE
Can't start on MacOS

### ISSUE THREAD

**Issue by svzi** [NativeScript/sidekick-feedback#26]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When I start NativeScriptSidekick, the app itself mentions that NodeJS 6.0.0+ is required, and it detects version 4.2.1. I don't know where the information is coming from, because when I run `node --version` I get the following output: `v6.9.5`. NPM is version 5.3.0. NativeScript 3.1.3.

### Which platform(s) does the issue occur on?
macOS (10.12.6 )

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** not sure how to check, because the app isn't really running.
- **NativeScript CLI:** 3.1.3
- **CLI extension nativescript-cloud:** not sure how to check
- **CLI extension nativescript-starter-kits:** not sure how to check

### Tell us how to recreate the issue in as much detail as possible.
1. Start the application via command line

### Does this issue happen every time?
Yes

### Send the client logs.
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_

No client logs available. Only output from terminal:

```
bash: no job control in this shell
Saving session... does not match regex.
...copying shared history... does not match regex.
...saving history... does not match regex.
...completed. does not match regex.
Deleting expired sessions...none found. does not match regex.
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/NativeScriptSidekick.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/Applications/NativeScriptSidekick.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/Applications/NativeScriptSidekick.app/Contents/Resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process._fatalException (bootstrap_node.js:300:26)
``` 

Any help would be really much appreciated.

Best,
Sven

**Comment by ventsislav-georgiev** [comment]
@svzi this issue is related to the default shell of the user account and its configuration files. Here is a similar issue reported on Ubuntu https://github.com/NativeScript/sidekick-feedback/issues/3.

The following information may help you resolve it:
* Set the default shell for your user account to match the one in your terminal `chsh -s $SHELL`

`echo $SHELL` should be something like `/bin/bash`, `/bin/zsh` etc.
* The Sidekick launches the default shell as `interactive` and a `login` by `$SHELL -il` and gets the `$PATH` variable from it. In a login bash shell the `.bashrc` file is not read, thus any configuration as the one `nvm` is setting is not used, so you should move any configuration from the `.{{shell}}rc` file to the `.{{shell}}_profile` file or source the `.{{shell}}rc` in the `.{{shell}}_profile`.

Could you provide the following information regarding your environment:
* terminal app: terminal, iTerm etc.
* shell: bash, zsh etc. and is it set as default for your user account or just the terminal app is configured to launch it?
* node version manager: n, nvm etc.

**Comment by svzi** [comment]
Thanks @ventsislav-georgiev, you pointed me in the right direction. My $SHELL variable wasn't properly set, it still pointed to `bash` instead of my current shell called `fish` (see: https://fishshell.com/). After I fixed that, I was finally able to start `NativeScript Sidekick`!

**Comment by lyndseypadget** [comment]
I am running zsh on Ubuntu 16.04.  After fussing with Node (uninstalling nvm) it still would not recognize my NativeScript CLI.  After reading #3 and #56, I found that the explanation offered here by @ventsislav-georgiev was the most helpful in understanding what Sidekick is actually doing during startup.

Like @svzi, my `$SHELL` variable was also set incorrectly (to `/bin/bash` rather than `/bin/zsh`).  Googling that reminded me that after running `chsh -s $(which zsh)`, one must **log out and back in** to a new desktop session in order for it to take effect!  Sidekick is finally happy, and so am I.
