### ISSUE TITLE
Sidekick not starting under Windows 7 64 bit

### ISSUE THREAD

**Issue by tsonevn** [NativeScript/sidekick-feedback#260]
_From @WhiteTrashLord on September 6, 2018 14:13_

I hope it's okay to post this here.
I wanted to try out Sidekick. Sadly I really have big problems under Windows 7 64 bit.
It seems that Sidekick installed correctly.
My problem seems to be similar to this:
https://discourse.nativescript.org/t/cannot-accept-sidekick-terms-of-service-on-windows-10/4587

But I have the problem that I almost never see this Terms screen. I also cannot continue this dialog in case I can see it. Did you fix this problem or is there another problem?

_Copied from original issue: NativeScript/NativeScript#6244_

**Comment by ggarabedian** [comment]
@WhiteTrashLord, the issue reported in the discourse post should be resolved and you are most likely experiencing a different issue. 

To investigate this further, I would ask you to share the Sidekick logs. You can access them by following the steps outlined in the [Access the NativeScript Sidekick logs article](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs). Because you cannot run Sidekick, you should use the `Through file manager or terminal` option.

**Comment by WhiteTrashLord** [comment]
I can start Sidekick. But it won't show anything. Only when I click on About it will show me something.

Here are my logs:

[console_18-09-09_17-03-28.245.log](https://github.com/NativeScript/sidekick-feedback/files/2364356/console_18-09-09_17-03-28.245.log)
[main_18-09-09_17-03-30.910.log](https://github.com/NativeScript/sidekick-feedback/files/2364357/main_18-09-09_17-03-30.910.log)

**Comment by ggarabedian** [comment]
@WhiteTrashLord, thank you for sharing the requested logs. Unfortunately, they don't contain any specific error messages, only the information that the EULA (terms of service) is not yet accepted.

Are you by any chance running behind a proxy? If you do, you need to configure the NativeScript CLI by setting the URL of the proxy and its credentials. For more information, please see the [tns proxy set](https://docs.nativescript.org/tooling/docs-cli/general/proxy-set) command.

In case the information provided above is not helpful, I would ask you to enable the verbose logging for Sidekick by following the steps outlined below:
1) Ensure that Sidekick is not running (in the task manager as well) and delete the old files in `%appdata%\NativeScriptSidekick\Logs`.
2) Navigate to `%appdata%/npm/node_modules/nativescript/config` and open the `config.json` file that is in this folder.
3) Change `"DEBUG": false` to `"DEBUG": true`.
4) Start Sidekick, reproduce the problem and then completely stop Sidekick (from the task manager).
5) Send us the newly created log files.
6) Don't forget to set the `DEBUG` option to `false`, because otherwise you will notice significant drop in the performance of Sidekick due to the large amount of logging done.

**Comment by WhiteTrashLord** [comment]
With debug turned on the log looks much more helpful. I think this is the root of the problem: Unable to download latest EULA  ,  Request was unsuccessful. Server returned:  
Failed to get error from http request:  SyntaxError: Unexpected end of JSON input

[main_18-09-11_14-08-38.040.log](https://github.com/NativeScript/sidekick-feedback/files/2370875/main_18-09-11_14-08-38.040.log)
[console_18-09-11_14-08-35.622.log](https://github.com/NativeScript/sidekick-feedback/files/2370876/console_18-09-11_14-08-35.622.log)

**Comment by ggarabedian** [comment]
Thank you for capturing a verbose log of the issue. The `Failed to get error from http request: SyntaxError: Unexpected end of JSON input` error is a bit sporadic and shouldn't be causing this problem.

Having said that, we are still under the assumption that the issue is related to the fact that the EULA is not accepted. With this in mind, can you please open a command prompt, run the `tns accept eula` command and then try to launch Sidekick again.

**Comment by WhiteTrashLord** [comment]
Yes, I never accepted the EULA. I only saw this EULA dialog like 2 times. Then I couldn't accept it. Most of the time it didn't show anything.
I think the tns accept eula command worked. 1 time I saw a dialog to accept the Privacy terms. But I also cannot continue this step. Is there a tns command to accept the privacy terms?

**Comment by ggarabedian** [comment]
@WhiteTrashLord, unfortunately, the Privacy Terms cannot be accepted through the CLI because they are relevant only for Sidekick. 

At this point we are running out of ideas as to what might be causing this behavior. The fact that we cannot reproduce the issue locally and the lack of error messages even in the verbose log is not helping us much. With this in mind, can you delete the `Cache` and `Local Storage` folders from `%appdata%\NativeScriptSidekick\` and if this does not help, try to reinstall the Sidekick client.

**Comment by WhiteTrashLord** [comment]
I could not tick the check boxes in these dialogs. But after a re-installation I was somehow able to complete the whole process and start Sidekick. But I already uninstalled it now. Your Playground is very impressive. I hoped Sidekick could do even more than the Playground but it seems that this is not the case. I hope you will add many more functions to Sidekick in the future.

**Comment by teobugslayer** [comment]
Hi @WhiteTrashLord,

I am happy that the Playground works well for you. We designed the Playground and Sidekick to be complimentary tools and to be used together. Sidekick concentrates more on developing complex applications with rich plugins and building and publishing apps even for iOS on Windows. Playground is designed for quick experimentation with the technology.
