### ISSUE TITLE
Differences between Local and Cloud Build.

### ISSUE THREAD

**Issue by relez** [NativeScript/sidekick-feedback#262]
Hi guys, I am trying to publish an app to the stores and I am having some issues. If I choose` Local Build` Sidekick does not ask me for the password for the .p12 certificate and Apple rejects the build with this message: Invalid Provisioning Profile. If I choose `Cloud Build `it does ask me for the password and it uploads perfectly. How can I configure my app to be able to use `Local Build` in Sidekick?

In the case of Android, it asks me for Password/Alias/Alias Password, in the case of `Cloud Build`, only the password is required.

Whats the difference here? And what can I do to resolve this issues?

Thanks!

**Comment by ggarabedian** [comment]
Hello @relez,

The cloud builds for iOS are using the certificate and mobile provision that you have selected from the local file system (in the `Manage iOS Provisioning and Certificates` dialog). However, local iOS builds are taking the code signing assets from the keychain of the macOS system. 

The `Invalid Provisioning Profile` error usually indicates that you are trying to build a publish package with a `development` or `ad-hoc` certificate and provision, when you need to be using distribution ones. 

Based on this information, there are a couple of options that come to my mind:
1) You are using distribution certificate and mobile provision that are present only on the local file system and not in the keychain. This would explain why you can build successfully in the cloud and not locally. To resolve this, you need to add the respective certificate and provision to the keychain by double-clicking on them in the file system.
2) You do not have a distribution certificate and mobile provision, and the cloud builds are debug builds that work with development and ad-hoc code signing assets and the local builds are publish ones that don't work with such assets. This is the less likely option and to resolve it, you need to create a distribution certificate and mobile provision from the Apple Dev Center.

Regarding the Android case, I cannot seem to reproduce such behavior when testing locally. On my end, I am always prompted only for password no matter the type of build. Can you tell me what type of cryptographic identity you use and does it have more than one aliases inside it?

**Comment by relez** [comment]
Hi there, thanks for the response. I am using a .p12 for Android builds, which I got from AppBuilder before it was shot down.

For local builds, I have added the iOS Certificate to the Keychain in MacOS, but the Provisional Profile can not be added to the Keychain, it only could be added to the project in Xcode.

I have read there is a filed `build.xcconfig` which you can indicate the team ID, certificate and provisional profile for local builds, but its not working for me. If a working example is provided that would be awesome.

Thanks!

**Comment by tsvetie** [comment]
Hi @relez,
I apologize for the late reply. 

Regarding the different information that we request for Android release builds - password, alias and alias password for local builds and only password for cloud build - you are correct, this is how Sidekick and NS CLI currently work.

Now, for the local iOS build - NS CLI supports passing the provision as a parameter to the build command, however, Sidekick does not support this yet. The only way you can specify the provision manually, is to edit the build.xcconfig file. You can follow these steps in order to do so:
1. In your app folder, navigate to app/AppResources/iOS and open the build.xcconfig file.
2. (Optional) If the build.xcconfig file does not exist, create it manually.
3. You can specify team ID, certificate and provisional profile the following way:
a. DEVELOPMENT_TEAM = YOUR_TEAM_ID
b. CODE_SIGN_IDENTITY = YOUR_CODE_SIGN_IDENTITY
c. PROVISIONING_PROFILE = YOUR_PROVISIONING_PROFILE

**Comment by ggarabedian** [comment]
Closing the issue due to inactivity. Please, consider opening a new issue if you continue to experience the problem with the latest version of NativeScript Sidekick.
