### ISSUE TITLE
Two-factor verification preventing auto-generated provisions

### ISSUE THREAD

**Issue by epearson15** [NativeScript/sidekick-feedback#289]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I'm trying to develop for iOS, however two-factor verification is activated. Due to Apple's updates to security, I'm unable to turn this off. When I go to auto-generate a provision for the device, I'm unable to because of two-factor verification. I currently don't have an Apple Developer provision, and I'm merely trying to test if Sidekick will work for my team's needs.

### Which platform(s) does the issue occur on?
iOS
Windows 10

### Provide the following version numbers that the issue occurs with:

Sidekick Version: 1.13.0-v.2018.10.5.2 (latest)
NativeScript CLI version: 4.2.4
CLI extension nativescript-cloud version: 1.14.2
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Start Sidekick
2. Connect an iOS device that has two-factor verification active
3. Click on the settings gear by the device name
4. Choose auto-generate

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.github.com/epearson15/de37cc8075534c03d0a03c22af4aaaf7

**Comment by ggarabedian** [comment]
Hello @epearson15,  

The Code Signing Assistance currently does not work with paid Apple IDs exactly due to the two-step verification feature used by Apple. Introducing support for paid Apple IDs for the automatic generation of iOS certificates and mobile provisions is on our roadmap, but due to the complex nature of the feature, we cannot give you a precise time frame for when it will be available.

Having said that, to test the Code Signing Assistance you should create a [new Free Apple ID](https://appleid.apple.com/account#!&page=create) and use it to generate the temporary code signing assets.

I hope this helps!

**Comment by epearson15** [comment]
Thank you for the advice! I'm finally able to use Sidekick with my iOS device. Thank you for all your help!
