### ISSUE TITLE
MacOS Sidekick

### ISSUE THREAD

**Issue by stan79** [NativeScript/sidekick-feedback#293]
Hiya

I have installed Sidekick on MacOS. It wasn't a smooth process (some issues with Python version etc) but I have finally managed to install it.
At the startup I am prompted to login using my Telerik account.
When I try to login using my Google account I get following error:

![screen shot 2018-11-04 at 21 16 45](https://user-images.githubusercontent.com/10582745/48086336-87b73200-e1f4-11e8-9563-68926f1efe45.png)

When I try to create Telerik account I seem to be getting into some infinite loop :) I seem to have a Telerik account (which I dont recall creating) but since I dont remember the password I am using password remainder functionality. I then receive an email with the link to activate my account. Upon clicking I get a message reading my account is now activated. After any navigation however there is no evidence of me being logged and I am prompted to create new account (however I cannot use same email as apparently I already have an account).

Not the best first impression :( 

Did anyone have same/similar issues?!?

**Comment by ggarabedian** [comment]
Hello @stan79,

I am sorry to hear that you have encountered such difficulties when setting up Sidekick.

Regarding the issue with the various accounts - when you sign in with your Google account, Sidekick uses the same email address to create a Telerik account and logs you with it. However, this account can be used only to sign in through the Google account and you cannot restore its password.

As for the error that you receive when you try to log in with the Google account, the issue is most likely occurring due to the fact that your current macOS user doesn't have access to the folder printed in the error message. Sidekick needs to store user related information there so it can log you in and keep the session running until you log out. Usually, this error can occur when you have installed Node, the NativeScript CLI or Sidekick with one user and use them with another, which does not have access to the specific folder. With this in mind, can you please check if your current user has permissions to write in the specific folder and in case he doesn't have access, provide him with such.

Please, let me know if this helps.

**Comment by stan79** [comment]
Yup, you were spot on. I simply dismissed authorisations as I've noticed NativeScript CLI subfolder and assumed that since that works fine, access error is just a red-hearing.
I have added Read-Write access to share folder for my user which seemed to have done the trick. I did however install everything else (including NativeScript CLI) using same user so it is a little confusing. Anyway, happy to report it works like a charm now.

Many thanks for your help :)
