### ISSUE TITLE
vs2017 extension: impossible to run/debug, throws "startup project cannot be launched"

### ISSUE THREAD

**Issue by isc30** [NativeScript/sidekick-feedback#294]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I'm using VS2017 sidekick extension and I can't run/debug from visual studio because the startup project cannot be launched.

### Which platform(s) does the issue occur on?
Windows 10

### Provide the following version numbers that the issue occurs with:

- **Sidekick for Visual Studio: 0.50** 
- **NativeScript CLI: 5.0.0** 
- **CLI extension nativescript-cloud: 1.14.2** 
- **CLI extension nativescript-starter-kits: 0.3.5** 

### Tell us how to recreate the issue in as much detail as possible
1. Create a new angular project from the extension templates
2. Compile using local android
3. F5 / press Run

### Does this issue happen every time?
_Yes_

**Comment by teobugslayer** [comment]
Hello @isc30 ,

Can you give us exact steps to reproduce the case?

**Comment by teobugslayer** [comment]
Hello @isc30,

As there was not sufficient demand for the Sidekick for Visual Studio extension, we decided to stop developing it. We will remove the extension from the marketplace and I strongly recommend you to uninstall it form within VS.

That said, the team is fully committed to continue developing the existing Visual Studio Code extension. It is our suggested way to develop NativeScript apps. That's why my suggestion is to try Visual Studio Code for developing your apps. Please note that at this time we have not exposed the cloud builds and associated services in the extension for Visual Studio Code. If you want to use the cloud builds, please consider installing the stand-alone Sidekick product from [here](https://www.nativescript.org/nativescript-sidekick)

Todor Totev
Product Manager
NativeScript Sidekick
