### ISSUE TITLE
Cannot install nativescript-cloud

### ISSUE THREAD

**Issue by teobugslayer** [NativeScript/sidekick-feedback#31]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When installing nativescript cli, this error appears:

```
Error while loading nativescript-cloud is: Cannot find module 'chokidar'
removed 573 packages in 145.877s
```

### Which platform(s) does the issue occur on?
N/A
Windows

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 3.1.3 
- **CLI extension nativescript-cloud:** It cannot be installed
- **CLI extension nativescript-starter-kits:** I don't know

### Tell us how to recreate the issue in as much detail as possible.
```npm i -g nativescript```
I am using node 8.3.0 and npm ver 5.3.0.

### Does this issue happen every time?
Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

 - _Windows: %AppData%\NativeScriptSidekick\Logs_
 - _macOS: ~/Library/Application Support/NativeScriptSidekick/Logs_
 - _Linux: ~/.config/NativeScriptSidekick/Logs_

**Comment by rosen-vladimirov** [comment]
Hey @teobugslayer ,
This is a problem with `npm 5` itself. In some cases it does not install all required packages during `npm install`, but the operation is reported as successful.
The solution is to reinstall the incorrect package. In this case I would recommend reinstalling `nativescript` itself:
```
$ npm uninstall -g nativescript
$ npm install -g nativescript
```

In some cases the same issue may occur in case CLI is installed correctly, but the `nativescript-cloud` extension has some issues. In this case you can uninstall it and start NativeScript Sidekick, which will install the required version:
```
$ tns extension uninstall nativescript-cloud
```

**Comment by teobugslayer** [comment]
After following the instructions (in npm@5 I needed to use `npm cache clean --force`) Sidekick ran and updated itself after which the error reappeared. Logs are attached.

[Logs.zip](https://github.com/NativeScript/sidekick-feedback/files/1224259/Logs.zip)

**Comment by teobugslayer** [comment]
As a work-around, I did `npm i -g chokidar` which enabled Sidekick to load without any warnings and I verified that cloud builds work.

**Comment by rosen-vladimirov** [comment]
In the recent days we have found one cause of this issue - in some cases npm does not remove all temporary packages in the globally installed modules. During `npm install`, several directories with names `.<package name>.<capitalized string>` are produced. For example you will receive `.nativescript.MODULES` directory, in which there are different packages required for the installation. Once the installation is finished, this directory must be removed. In some cases, such temp directories are not removed and they cause issues in consecutive installations of the same package.
In order to determine if this is the cause of the problem, you can try changing the place where global modules are installed:
```
$ npm config get prefix // This will print current directory for global installations}
$ npm config set prefix <some dir>
$ npm install -g nativescript@next // install some version of nativescript package
$ npm install -g nativescript@latest // install the latest version - problems often rise when the package is just updated
// Start Sidekick and test it. 
$ npm config set prefix <dir from step 1> // get back the real directory for globally installed packages.
```
If everything works correctly, check the `<dir from step 1>/node_modules` directory for any temporary directories (like `.nativescript.DELETE`, `.nativescript.MODULES`, etc.) and if there are any - just delete them. After that install latest version of CLI again and check if the issue is resolved.
