### ISSUE TITLE
Unreachable connected device

### ISSUE THREAD

**Issue by bradrice** [NativeScript/sidekick-feedback#311]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I have listed under connected devices, Unreachable

### Which platform(s) does the issue occur on?
Mac OS 10.14.2

### Provide the following version numbers that the issue occurs with:

Version: 1.14.1-v.2018.11.23.3 (latest)
NativeScript CLI version: 5.0.1
CLI extension nativescript-cloud version: 1.14.4
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
I don't know how it happened. I'm assuming a device crashed while I was using Nativescript. I've tried launching the device I thought it was.

### Does this issue happen every time?
Yes. I've restarted the NativeScript Sidekick app and it remains.

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs]
![screen shot 2018-12-14 at 9 35 02 am](https://user-images.githubusercontent.com/272352/50008953-a6db7900-ff83-11e8-93dc-c0156bb302b0.png)

[console_18-12-14_09-15-22.629.log](https://github.com/NativeScript/sidekick-feedback/files/2680411/console_18-12-14_09-15-22.629.log)

**Comment by ggarabedian** [comment]
@bradrice, I am not able to reproduce the described behavior when testing iOS 10, 11 and 12 devices on a macOS 10.14.2 machine with iTunes 12.9.2.5 installed. Can you please check if the device is discovered and recognized correctly by iTunes as this will help us determine if the issue is on Sidekick or device/OS level?

Additionally, devices are most commonly shown as unreachable when you haven't trusted them. If the _trust device_ popup is not appearing, you might want to reset the _Location & Privacy_ settings of your device by following the steps under [Change your settings for trusted computers](https://support.apple.com/en-us/HT202778).
