### ISSUE TITLE
Where are cloud builds stored, what security is in place, how do I remove uploaded data?

### ISSUE THREAD

**Issue by tozz** [NativeScript/sidekick-feedback#313]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
When using cloud builds there's no way of listing previous builds, delete them or even see any kind of log. I have no idea what is being uploaded, how long it's stored or what procedures are in place to protect it.
This also goes for failed builds.

Do I need to delete my Telerik account to delete my data?

### Which platform(s) does the issue occur on?
macOS (but probably all)

### Provide the following version numbers that the issue occurs with:
NativeScript Sidekick Desktop

### Tell us how to recreate the issue in as much detail as possible
1. Start the application
2. Use Cloud Build

### Does this issue happen every time?
Yes

**Comment by ggarabedian** [comment]
Hello @tozz,

You cannot find a listing of previous builds because we do not associate builds with the specific users that execute them. This is done for security reasons, specifically to ensure that we do not store any user related information on our build machines. 

As to what is uploaded to our cloud infrastructure, that would be only application and code signing data. The information is stored for 7 days and then deleted. During the 7 days period this data is used as incremental builds cache, a feature which vastly improves the build times of the applications. I would like to note that you can forcefully purge this information at any given time through the `Clean Cloud Workspace` option. This app specific option can be accessed from the `File` menu in the top toolbar (while the app is open) or from the settings cogwheel for the specific application in the app listing view.

I hope this helps.

**Comment by tozz** [comment]
@ggarabedian Thank you for the clarifications, I think this information should be central in the documentation, I googled for an hour trying to find anything regarding this and turned up nothing.
