### ISSUE TITLE
Sidekick publish to iOS hangs

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/sidekick-feedback#318]
Hello,

I am trying to publish to iOS from a Windows 10 machine, but I am having some issues.  The Sidekick builds successfully, but then it just hangs after I enter our iTunesConnect credentials.  I have tried leaving it for a couple of hours without any success.  At the end, I have to close the Sidekick in order to stop the operation.  I do not see any errors in the console. I am using:

`Version: 1.14.1-v.2018.11.23.3 (latest) 

NativeScript CLI version: 5.1.0
CLI extension nativescript-cloud version: 1.14.4
CLI extension nativescript-starter-kits version: 0.3.5`

I saw several posts related to the new 2FA Apple is enforcing on all new accounts (our account has that).  Is this still an issue with Sidekick?  If this is the case, what are my options for deploying from Windows?  Someone mentioned http://www.appuploader.net/index.php,  has anyone tried them?

Thanks.

**Comment by ggarabedian** [comment]
@dpdragnev, unfortunately yes, two factor authentication is still not supported and accounts that use it cannot publish or create temporary code signing credentials through Sidekick. We are aware of the impact of this limitation (especially since Apple now enforce 2FA) and we are currently working on introducing support for this scenario in Sidekick.

**Comment by dpdragnev** [comment]
Thank you @ggarabedian 

How do you suggest we do the upload to iTunesConnect?

**Comment by ggarabedian** [comment]
@dpdragnev, we would recommend that you use a macOS system to publish the IPA as an alternative to Sidekick.

We haven't used services like AppUploader, so I cannot really give you an opinion about it. The biggest concern would be how secure is the service as there is no way to be sure that the IPA is going only to iTunesConnect. If you upload **only** the IPA and no certificates/mobile provisions it might be a viable alternative, however, I still cannot recommend the service due to the fact that we don't have first hand experience with it.

**Comment by dpdragnev** [comment]
Thank you @ggarabedian,

I will fire up my iMac and publish from there.

Happy New Year!
