### ISSUE TITLE
Can't install on the iPad from windows

### ISSUE THREAD

**Issue by sandoche** [NativeScript/sidekick-feedback#319]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
* I created the right development certificates and provisioning profiles for this ipad
* The ipad is well detected
* But it blocks at the install (see screenshot below)
![image](https://user-images.githubusercontent.com/3635348/50536649-ddee8480-0b56-11e9-89f4-cce1ee3acd0b.png)

### Which platform(s) does the issue occur on?
iOS
Windows

### Provide the following version numbers that the issue occurs with:
Version: 1.14.1-v.2018.11.23.3 (latest)
NativeScript CLI version: 5.0.2
CLI extension nativescript-cloud version: 1.14.4
CLI extension nativescript-starter-kits version: 0.3.5

### Tell us how to recreate the issue in as much detail as possible
1. Plug the ipad
2. Select profiles
3. Run

### Does this issue happen every time?
Yes

### Send the client logs
https://gist.github.com/sandoche/07d2a160f29ee28f1836d5acfec34fbe

**Comment by sandoche** [comment]
Actually after cleaning the build from the `.cloud` folder manually it worked.
So I guess the "Clean build" checkbox is not working.

**Comment by ggarabedian** [comment]
@sandoche, the `Clean Build` option is used to clear any artifacts and app data cached on the cloud machine and completely rebuild the application. This option does not modify the contents of your local app folder in any way. That's the reason why some sporadic build failures caused by corrupted local files can be resolved only by deleting the `node_modules`, `platforms` or `.cloud` folders. 

Based on your description, the issue is most likely related to the fact that you have previously built the app for an iPhone device and the produced `IPA` has been stored in the `.cloud` folder. When you attach another device (in this case and iPad), Sidekick checks if there are any changes to the code and if none exist, directly attempts to install the `IPA` on the device.

I hope this is of any help. In any case, I am happy to hear that you were able to resolve the issue!.
