### ISSUE TITLE
Nativescript CLI 5.1.1 installed, but Sidekick fails to recognise it. Sidekick fails to open.

### ISSUE THREAD

**Issue by subbutrms** [NativeScript/sidekick-feedback#332]
## Please, provide the details below:
On Ubuntu 14.04, Sidekick fails to start. It says "Nativescript CLI is required", though Nativescript CLI is installed. tns info is able successfully locate nativescript cli.

Here is *tns info* output:
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.1.1 version and is up to date.

Here is the *npm list -g nativescript* 
output:
npm list -g nativescript
 /home/subbu/.npm-global/lib
└── nativescript@5.1.1 

### Did you verify whether this issue has already been reported here?
Yes
### Tell us about the problem
Installed sidekick by downloading the official latest deb file "NativeScriptSidekick-amd64.deb". But it fails to open, complaining Nativescript cli is required.

### Which platform(s) does the issue occur on?
Ubuntu 14.04

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** v1100---23-may-2018
- **NativeScript CLI:** v5.1.1
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start Sidekick by opening it via ubuntu menu (dash)
2. It displays a prompt saying Nativescript CLI is required.
![selection_008](https://user-images.githubusercontent.com/24863336/51690695-39f5dd00-201f-11e9-90d1-db3eebb7c6a9.png)

### Does this issue happen every time?
Yes

### Send the client logs
[console_19-01-24_21-19-50.564.log](https://github.com/NativeScript/sidekick-feedback/files/2792450/console_19-01-24_21-19-50.564.log)
[main_19-01-24_21-19-52.671.log](https://github.com/NativeScript/sidekick-feedback/files/2792452/main_19-01-24_21-19-52.671.log)

**Comment by ggarabedian** [comment]
Hello @subbutrms,

It appears that for some reason Sidekick is not able to identify the correct path to the NativeScript CLI. Can you please run the `which tns` command in the terminal and share the produced output in your next response?

I would like to note that the minimum supported version for Sidekick is Ubuntu 16.04. However, in this case, we don't think that the issue is related to the OS version and we would like to investigate it further.

**Comment by subbutrms** [comment]
Hi @ggarabedian , Thank you for your response.
Surprisingly, "which tns" does NOT return anything in the command prompt.

```
subbu:~$ which tns
subbu:~$ 
```
But as I mentioned in my previous comment, "tns info" works well:

```
subbu:~$ which tns
subbu:~$ tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.1.1 version and is up to date.
subbu:~$ 
```

**Comment by ggarabedian** [comment]
@subbutrms, the only thing that comes to our minds and explains this behavior is the use of an alias. 
For Sidekick to work properly, the folder that contains the `tns` executable needs to be included in `PATH` and using an alias will most likely break this. 

Can you tell me if you've made any aliases of `tns`?  You can list all the aliases you have by running the `alias` command.

**Comment by subbutrms** [comment]
Hi @ggarabedian , No, I do not have any aliases set up.
`subbu:~$ alias

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'

subbu:~$ `

**Comment by ggarabedian** [comment]
@subbutrms, in this case, we are not certain what might be causing this behavior. You might want to check the first answer in [My `which` command may be wrong (sometimes)?](https://unix.stackexchange.com/questions/47363/my-which-command-may-be-wrong-sometimes) and see if the information there helps you in some way.

I am sorry that we cannot be of much assistance, but the issue seems to be related to something specific in your environment and we cannot reproduce it on our end.

**Comment by NickIliev** [comment]
@subbutrms please try to update to latest version of NativeScript CLI and Sidekick. Closing the issue due to inactivity but please do let me know if you still experience this one.
