### ISSUE TITLE
2FA support - when?

### ISSUE THREAD

**Issue by webcoderkz** [NativeScript/sidekick-feedback#346]
Sidekick isn't compatible with 2FA when pushing app to AppStore, or getting autogenerated certificates. Is there ETA for this must have feature?

**Comment by teobugslayer** [comment]
We are working on this feature but no ETA yet.

**Comment by heihachi88** [comment]
So we have only 2 choices left then - xcode and Application loader?

**Comment by ggarabedian** [comment]
@heihachi88, we are aiming to release this by the end of February. However, our QAs are still testing the feature and if needed, the release might be postponed for March. Having said that, we will definitely introduce support for 2FA, but it might be delayed until mid-March.

Until then, the options you have mentioned are the only alternatives to publish from an account with 2FA enabled.

**Comment by ggarabedian** [comment]
@heihachi88, yesterday we released a new version of Sidekick, which includes support for 2FA for **publishing**. 

We are still investigating what are our options to provide 2FA for the code signing assistance (auto generating certificate and mobile provision), because it would require a different implementation than the one we use for the publish.
