### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by tomo54321** [NativeScript/sidekick-feedback#411]
### Did you verify whether this issue has already been reported here?
_Yes_

### Tell us about the problem
I've been logged out of SideKick so I go to log back in and it keep getting this error - 
![image](https://user-images.githubusercontent.com/20615869/62275597-34e47100-b43a-11e9-815c-a3475b5b63eb.png)
 
I have gone through the list given in the error and only cloud-operation.nativescript.cloud isn't working. I've gone and tried on another machine with a different internet connection and I keep getting the same result. 

I've also tried logging in with Google and GitHub and both get to "Connecting..." and eventually will just timeout. 

### Which platform(s) does the issue occur on?
_Windows 10_

### Provide the following version numbers that the issue occurs with:
![image](https://user-images.githubusercontent.com/20615869/62275748-81c84780-b43a-11e9-8dc3-d2e687bbb89f.png)

### Tell us how to recreate the issue in as much detail as possible
1. Start the application
2. Login
3. Wait for it to fail

### Does this issue happen every time?
_Yes_

**Comment by tsvetie** [comment]
Hello @tomo54321,

Can you try the following:
1. Open your default browser and open DevTools. Go to the Network tab.
2. Open the following URL: `https://authentication.nativescript.cloud/v4/api/login`

In case the problem was temporary, you should be able to open the page. Otherwise, you can check which request exactly fails and then check with your system admins what to whitelist.

Since this could take some time, as a workaround, you can login through NS CLI. In order to do this, open a Terminal/Command Prompt and execute `tns dev-login <Email> <Password>`. After that, when you open Sidekick, you should already be logged in.

**Comment by tomo54321** [comment]
Hi there,

I have managed to open the page which worked, however I was still unable to login when using SideKick directly. 

Once I used the workaround you provided, I was logged back in. Thank you! :)
