### ISSUE TITLE
Unable to Install NativeScriptSideKick on Manjaro Linux

### ISSUE THREAD

**Issue by SyedFaraz55** [NativeScript/sidekick-feedback#413]
```
[syed@syed-pc Downloads]$ sudo dpkg -i NativeScriptSidekick__amd64.deb 

(Reading database ... 5323 files and directories currently installed.)
Preparing to unpack NativeScriptSidekick__amd64.deb ...
Unpacking nativescriptsidekick (1.19.0-v.2019.7.25.4-46) over (1.19.0-v.2019.7.25.4-46) ...
Error in file "/usr/share/applications/code-oss-url-handler.desktop": "x-scheme-handler/@@URLPROTOCOL@@" is an invalid MIME type ("x-scheme-handler/@@URLPROTOCOL@@" contains an invalid character in the subtype)
dpkg: dependency problems prevent configuration of nativescriptsidekick:
 nativescriptsidekick depends on gconf2; however:
  Package gconf2 is not installed.
 nativescriptsidekick depends on gconf-service; however:
  Package gconf-service is not installed.
 nativescriptsidekick depends on libnotify4; however:
  Package libnotify4 is not installed.
 nativescriptsidekick depends on libappindicator1; however:
  Package libappindicator1 is not installed.
 nativescriptsidekick depends on libxtst6; however:
  Package libxtst6 is not installed.
 nativescriptsidekick depends on libnss3; however:
  Package libnss3 is not installed.

dpkg: error processing package nativescriptsidekick (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 nativescriptsidekick

[syed@syed-pc Downloads]$ 
```

**Comment by NickIliev** [comment]
@SyedFaraz55 it seems that the issue is related to a local configuration and missing dependencies. Can you send us the generated Sidekick log?

Please, when posting new issue following the "New Issue" template so that all needed information is provided

## Please, provide the details below:

### Did you verify whether this issue has already been reported here?
_Yes/No_

### Tell us about the problem
_Give us a concise description of the feature you suggest or the issue you report._

### Which platform(s) does the issue occur on?
_iOS/Android/Both (if applicable, tell us the specific version of the platform)_ <br/>
_Windows/macOS/Linux/Multiple (if applicable, tell us the specific version of the platform)_

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick:** 
- **NativeScript CLI:** 
- **CLI extension nativescript-cloud:** 
- **CLI extension nativescript-starter-kits:** 

> _How to obtain this information is explained in the [Gather information about your development environment](https://github.com/NativeScript/sidekick-feedback#gather-information-about-your-development-environment) section._

### Tell us how to recreate the issue in as much detail as possible
1. Start the application ..
2. ...

### Does this issue happen every time?
_Yes/No_

### Send the client logs
>_How to obtain the Sidekick logs is explained in the [Access the NativeScript Sidekick logs](https://github.com/NativeScript/sidekick-feedback#access-the-nativescript-sidekick-logs) section. To share them with us, you can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs and send the produced link._
