### ISSUE TITLE
service api.npms.io is not available

### ISSUE THREAD

**Issue by artificemm** [NativeScript/sidekick-feedback#490]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem
I opened sidekick to check on a plugin for my project. Click on the link provided, went to the browser to read the documentation, and on return, sidekick seems to timeout the connection and throws this:
"[20-06-02 16:24:15.029] The service api.npms.io is not available. Try using NativeScript CLI to install and manage plugins."

This was not happening before, because I am spending some time reading the docs of the plugins and experimenting, then going back to Sidekick to install/search another.

Restarting seems to alleviate it.

### Which platform(s) does the issue occur on?
macOS

### Provide the following version numbers that the issue occurs with:

- **NativeScript Sidekick: Version: 1.20.0-v.2020.6.1.1 (latest)
### Tell us how to recreate the issue in as much detail as possible
1. Start the application Sidekick
2. Go to your project's plugins
3. Go to available and search anything
4. Spend some time out of Sidekick, around 20-25 minutes
5. Try searching for some other plugin and click for the info

### Does this issue happen every time?
Yes

**Comment by rosen-vladimirov** [comment]
Hey @artificemm ,
Thanks for reporting this. The issue was on npms.io side, we've reported it and they've fixed it. Meanwhile, we've applied a fix in version 1.20.1 of NativeScript Sidekick - now we use the registry.npmjs.org API instead of npms, so such issue shouldn't occur in the future (or if it doesn't work in Sidekick, it will not work in https://www.npmjs.com as well.

I'm closing this issue as resolved. Feel free to reopen it in case you still have any problems with the npm search.

**Comment by artificemm** [comment]
Thank you very much! 👏
