### ISSUE TITLE
Run on Device / Livesync / Debug iOS on Windows

### ISSUE THREAD

**Issue by simplec-dev** [NativeScript/sidekick-feedback#54]
This is about run on device for iOS on my Windows machine. 

I'm having issues with livesync / debug.  When I do a "run on device" (cloud / debug) on for iOS, it will:
 - build
 - download the IPA
 - install it on the phone (though much slower than a tool like iTools)

If I don't check "start debugging", it doesn't start the app automatically.  

If I check "start debugging", I get this error:[17-09-27 09:28:08.354] 
(Error) The application com.simplec.companion.phone.dev does not appear to be running on Doug’s iPhone or is not built with debugging enabled., Error: The application com.xxxxxxxxxx.dev does not appear to be running on Doug’s iPhone or is not built with debugging enabled.
    at DevicesService.<anonymous> (C:\Users\doug.nelson\AppData\Roaming\npm\node_modules\nativescript\lib\common\mobile\mobile-core\devices-service.js:273:38)

So, if I start the app first, every once in a while, I will see safari pop, then I might get the debug window.

But I cannot figure out the pattern.  I know this is a work in progress, so this is not a complaint.

It would be helpful to have a short guide that explains the pattern to get it running in livesync or debug mode on iOS from Windows.  The docs are pretty thin.

**Comment by ndinev** [comment]
Try this:
-- in Sidekick open device pane to see your attached devices
-- Just do run on device with cloud build and debug - you app is not started on the device
-- Start app manually on the device and wait to be fully loaded
-- Then in Sidekick there is a small "bug" icon next to your device. Click it - this should start debugger

**Comment by simplec-dev** [comment]
I'm on the latest public release of sidekick and don't see a bug icon.  The only thing I see is a green lightning bold inside the device icon.  I assume that means livesync is (theoretically) started.

**Comment by tsvetie** [comment]
@simplec-dev Now that you put it that way, I can understand very well why you are a bit confused :). Let me try to explain the process. 

First of all, you can find the "bug" icon/button is in the Devices panel - select the Devices tab in the bottom right corner of the Sidekick app and you will see it. You can use this button to start a debug session at any time.

Now, here is some insight on the LiveSync + Debugger combination - when you use Run on device in Debug mode, we start LiveSync - it will make sure that the latest version of the app is on the device and watch for file changes. Additionally, it will try to start the app on the device. For some iOS devices, we can start the app, for others - we cannot (in these cases you should see a message in the Output saying that you should start the app manually). This depends on whether we can find developer disk image on the device.

Now, regarding the debugger. In case the app is the active application on the device, we can start a debug session. If you check the "Start debugger" checkbox in the Run on device view, we will try to start a debug session after we start LiveSync and we will fail, as your device has no developer disk image and we cannot open the app on the device. This will work as expected, in case we can - e.g. for Android devices and iOS devices with developer disk image.

Finally, in case LiveSync is enabled and a debug session is started, when you change the code of your app, we will sync the changes to the device and try to restart the app so that you can see the changes and we can reconnect the debugger. As we cannot start the app in your case, we do the next best thing - we prompt you to do it for us by opening a page in Safari.

**Comment by ndinev** [comment]
Lets confirm - the version in the output pane should be : Version: 0.2.4-v.2017.9.15.8
Then when device is connected you should be able to see this: https://www.screencast.com/t/FqsYP3iv6d

**Comment by simplec-dev** [comment]
That helps guys.  I think it would be worthwhile to put some of that in the docs.

I can debug effectively now.

The livesync is still a little wonky to me.  It doesn't appear to refresh automatically.  It seems like I need to unplug the USB cord to reset the connection periodically.

Also, it looks like debugging sessions get lost if another app comes to the forefront.  I had to put my phone on do not disturb today to prevent texts and phone calls.

Thanks again.  If you have any tips for keeping livesync "live" let me know.

BTW - great start on extending a solid tool set.

**Comment by tsvetie** [comment]
Thanks for the note - we will make sure to explain this in the documentation.

About the LiveSync - can you give us more information what happens? In case LiveSync fails at some point, you should get an error in the Output stating that LiveSync stopped and information about the error. Do you see any errors?

On a side note, some changes cannot be LiveSynced quickly and the LiveSync process first performs a new build. In these cases, you will see the changes on the device after a couple of minutes.
