### ISSUE TITLE
Build failed with iOs cloud build - Run on device

### ISSUE THREAD

**Issue by bonfi7** [NativeScript/sidekick-feedback#63]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When I try to run the app on my iPhone I get "Command npm install tns-ios@3.2.0 --silent --save-exact --save failed with exit code 254" after a while. I can get the application run in local with android but with a cloud build in iOs I get this error.

### Which platform(s) does the issue occur on?
iOS
Windows

### Provide the following version numbers that the issue occurs with:
Version: 0.2.5-v.2017.9.27.4 (latest)
NativeScript CLI version: 3.2.1
CLI extension nativescript-cloud version: 0.13.0
CLI extension nativescript-starter-kits version: 0.1.16

### Does this issue happen every time?
Yes

### Send the client logs.
_The client logs can help us identify what is causing the issue. You can [create a gist](https://help.github.com/articles/creating-gists/) with the app logs. Based on your operating system, the logs are located in the following directories:_

[cli_17-10-10_09-13-31.292.log](https://github.com/NativeScript/sidekick-feedback/files/1371190/cli_17-10-10_09-13-31.292.log)
[main_17-10-10_09-13-16.147.log](https://github.com/NativeScript/sidekick-feedback/files/1371191/main_17-10-10_09-13-16.147.log)

**Comment by rosen-vladimirov** [comment]
Hey @bonfi7 ,
Thank you for sharing the logs. It looks like the project is in inconsistent state on our build machines. In order to have faster builds, we are persisting `node_modules` and `platforms` dir for some time on our build machines. In order to clean these files, you should start a clean build (use the checkbox in the UI). Can you try a clean build and see if it works on your side?

**Comment by bonfi7** [comment]
Hi @rosen-vladimirov , thank you for your fast reply. I already try with Clean Build but it doesn't work.  
It could be an issue related to the use of nativescript-nodeify? I attach also my package.json if it could help.
[package.txt](https://github.com/NativeScript/sidekick-feedback/files/1374504/package.txt)

**Comment by bonfi7** [comment]
Hi, any news on this?

**Comment by rosen-vladimirov** [comment]
Hey @bonfi7 ,
Please excuse me for the late reply. I've tried reproducing the issue on my side by using the package.json you've provided, but it has been successfully built on my side. We have applied a lot of changes in the last month, so may I ask you to try again and see if the issue is still reproducible on your side?
