### ISSUE TITLE
DVTAssertions: ASSERTION FAILURE

### ISSUE THREAD

**Issue by anakinjay** [NativeScript/sidekick-feedback#66]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
When I try and do a local build I get the following error:
**[17-10-13 09:46:19.762] (Error) Command xcodebuild failed with exit code null Error output: 
 2017-10-13 09:46:19.679 xcodebuild[40700:162511] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-13203/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/RuntimeSupport/MacroExpansion/XCMacroExpansionExtensions.mm:94**

### Which platform(s) does the issue occur on?
iOS - MacOS Sierra 10.12.6

### Provide the following version numbers that the issue occurs with:
_To get these version, click on Help/About_

- **NativeScript Sidekick:** 
0.2.5-v.2017.9.27.4(latest)

- **NativeScript CLI:** 
3.2.1

- **CLI extension nativescript-cloud:** 
0.1.8

- **CLI extension nativescript-starter-kits:** 
0.1.16

### Tell us how to recreate the issue in as much detail as possible.
Started with a brand new app from the template (have tried navigation blank, drawer, and tabs templates, haven't tried the others) and immediately try and build without making any modifications.

### Does this issue happen every time?
Yes

### Send the client logs.
[cli_17-10-13_09-46-03.226.log](https://github.com/NativeScript/sidekick-feedback/files/1382806/cli_17-10-13_09-46-03.226.log)

**Comment by anakinjay** [comment]
I'll add also that opening the xcode project generated by nativescript sidekick in actual xcode crashes xcode.

**Comment by Mitko-Kerezov** [comment]
Hi @anakinjay 

There is a [similar issue](https://github.com/NativeScript/NativeScript/issues/3633) in the NativeScript organization, which suggests adding your `DEVELOPMENT_TEAM` in `app/App_Resources/iOS/build.xcconfig` file in your project. Could you try adding that and see if it helps.

In case the suggested solution does not resolve the issue, I'd like to ask you to upload a sample application demonstrating the issue, so that the team can take a look at it. As a side note you could try executing the following commands in the terminal:
1. `tns create sampleApp`
1. `cd sampleApp`
1. `tns build ios --for-device`

In order to see whether the NativeScript CLI is able to build a project with your configuration at all. If that doesn't pass I suggest executing `tns doctor` in the terminal in order to diagnose and solve any configuration problems you might have.

Let me know if this helps.

**Comment by anakinjay** [comment]
@Mitko-Kerezov  thank you!  I *think* it was the team ID causing me issues, adding that to the build file *at least* is letting me "run on device" from sidekick.  I still can't do a local build but now it's talking about provisioning profiles and stuff that I'm pretty sure is just wrong on my end with xcode in general.

But setting that team ID allows me to develop locally with sidekick & the ios simulator so that was really what I was after.  Thanks again!

**Comment by duyhung85** [comment]
@Mitko-Kerezov My app development was working yesterday but now it suddenly showing this ASSERTION FAILURE error. I spent a few hours to fix it but no luck. 
1. I follow your guide to create fresh app and build but still having the same error. 
2. Also try to put the team Id in build.xcconfig but no luck
I am running on latest nativescript 5.1.0.

**Comment by ggarabedian** [comment]
@duyhung85, can you please open a new issue and share the entire build log there? The ASSERTION FAILURE can be related to various things and we cannot be certain what is causing the error without examining the whole build output.  

Additionally, there are several issues online that mention assertion failures that are related to a corrupted Xcode installation, so you might want to check this as well, especially if you have updated or otherwise modified your Xcode recently.

**Comment by duyhung85** [comment]
@ggarabedian Thank you for your reply! After follow this upgrading guide (which I did before but just go through it again): 
[https://docs.nativescript.org/releases/upgrade-instructions]

My app is back working now, so it may be caused by some corrupted packages.
