### ISSUE TITLE
JS runtime errors don't show up in the console or errors tab in Sidekick

### ISSUE THREAD

**Issue by ignaciofuentes** [NativeScript/sidekick-feedback#83]
This is happening on iOS Simulator on Mac using cloud build.
Using latest version of Sidekick and nativescript cli:

Version: 1.0.0-v.2017.11.6.3 (latest)
NativeScript CLI version: 3.3.0
CLI extension nativescript-cloud version: 1.0.0
CLI extension nativescript-starter-kits version: 0.3.4

Description of the problem:

XML errors are reported correctly as part of the UI of the app.
but JS errors are nowhere to be seen
I should expect something like:

> file:///app/home/home-page.js:19:12: JS ERROR ReferenceError: Can’t find variable: pagddde

but I just dont see such error anywhere.
here’s my screen recording

https://www.screencast.com/t/mCTFWxsRcW

**Comment by rosen-vladimirov** [comment]
Hey @ignaciofuentes , this is expected - the Output pane shows the output of Sidekick executions. In order to see your console logs, you have to click on the `Devices` pane and select the `Console` tab. That's where the device logs will be shown, so you'll see your errors and console logs there.

I'm closing this thread, feel free to reopen it in case you have any problems or concerns.
