### ISSUE TITLE
Importing external applications

### ISSUE THREAD

**Issue by gordingin** [NativeScript/sidekick-feedback#86]
I am trying to import this application

https://www.nativescript.org/blog/tinder-style-cards-with-nativescript---love-at-first-swipe

and get it to run it in SideKick. The import works but when I build, I get this error.

Error: Command npm.cmd install tns-ios@2.5.0 --silent --save-exact --save failed with exit code 1

Note, I AM able to create an app in sidekick and compile it so my system is configured correctly. Just not  sure how to debug this and make it work.

**Comment by tsvetie** [comment]
Possibly related to #86

**Comment by tsvetie** [comment]
@gordingin, the application you chose to start with is outdated and targets an old version of NativeScript. NaiveScript Sidekick does not support NativeScript 2.5.0. In order to use this application with Sidekick, you will have to migrate it first to NativeScript 3.0.0 or a newer version. In case you decide to take this path, please [review this article first](https://github.com/NativeScript/NativeScript/blob/master/Modules30Changes.md).
