### ISSUE TITLE
Local build loops endlessly with no additional feedback

### ISSUE THREAD

**Issue by EmilStoychev** [NativeScript/sidekick-feedback#94]
### Did you verify whether this issue has already been reported here?
Yes

### Tell us about the problem.
Upon trying to run an app on iOS device (emulator) using local build, I get Build started in the Output, then the spinner loops endlessly without any other feedback what's going on. 

### Which platform(s) does the issue occur on?
iOS
macOS

### Provide the following version numbers that the issue occurs with:
Version: 1.0.1-v.2017.11.16.1 (latest)
NativeScript CLI version: 3.3.1
CLI extension nativescript-cloud version: 1.0.0
CLI extension nativescript-starter-kits version: 0.3.4

### Tell us how to recreate the issue in as much detail as possible.
1. Clone https://github.com/NativeScript/sample-health-survey.git
2. Open in Sidekick
3. Run on device, choose local build, debug, select iOS emulator

The same app builds and runs fine using the CLI.

### Does this issue happen every time?
Yes

### Send the client logs.
[Archive.zip](https://github.com/NativeScript/sidekick-feedback/files/1492480/Archive.zip)

**Comment by tsvetie** [comment]
After some offline testing with @EmilStoychev, it turned out that we could no longer reproduce the problem. However, we did get the following error:

_Pod install command failed. Error output: 
Consider adding the following to ~/.profile:

export LANG=en_US.UTF-8_

After we added the export to the .bash_proflle, we managed to build the application as expected.

Related to #9
